In [1]:
import numpy as np


In [2]:
fi = []
with open('sensor_data.csv', 'r') as f:
    for i in f:
        data = i.strip().split(',')
        fi.append([float(x) for x in data])

In [3]:
n_array = np.array(fi)

In [4]:
n_array

array([[  21.21,   66.86,   47.73, ...,   60.63,   10.51,   83.58],
       [  47.24,   71.7 ,   68.44, ...,   68.91,   29.68,   38.72],
       [  39.07,   21.85,   31.86, ...,   12.77,   12.38,   16.5 ],
       ...,
       [  18.6 ,   64.89,   41.9 , ...,   16.49,   32.04,   36.97],
       [  22.03,   43.26,   55.61, ...,   13.56,   83.69,   61.68],
       [  45.06, -999.  ,   20.37, ...,   86.32,   35.03,   34.74]],
      shape=(720, 100))

In [6]:
n_array[n_array == -999] = np.nan

In [8]:
n_array[(n_array < 0) & (n_array > 100)] = np.nan

In [41]:
n_array

array([[21.21, 66.86, 47.73, ..., 60.63, 10.51, 83.58],
       [47.24, 71.7 , 68.44, ..., 68.91, 29.68, 38.72],
       [39.07, 21.85, 31.86, ..., 12.77, 12.38, 16.5 ],
       ...,
       [18.6 , 64.89, 41.9 , ..., 16.49, 32.04, 36.97],
       [22.03, 43.26, 55.61, ..., 13.56, 83.69, 61.68],
       [45.06,   nan, 20.37, ..., 86.32, 35.03, 34.74]], shape=(720, 100))

In [14]:
ms = np.nanmean(n_array,axis=0) # for columns we use axis = 0

In [24]:
print("mean moisture for each sensor is: ",ms)

mean moisture for each sensor is:  [50.73858198 50.2341159  51.27293413 49.0773494  50.26127246 49.66935725
 51.52051051 50.68205621 51.33179878 51.47947526 50.84037764 51.0440625
 49.26940916 51.26822653 49.37944193 49.71962798 49.21847988 49.3203139
 50.15004431 52.84455213 50.17457903 48.00882963 49.75005952 50.404003
 49.19879056 50.36595238 50.2916716  49.01795588 49.63189552 50.99672083
 50.95953731 49.36990991 50.82856509 50.03372372 51.63781627 51.60602679
 48.96136499 50.19457652 49.54323308 49.5746027  50.55213115 50.19353372
 50.19954876 49.76128743 51.57152207 49.78535127 51.35110783 48.45413534
 50.27472059 48.89479104 49.9655988  51.89755224 49.3852608  49.93882006
 49.58385757 51.64714925 48.61207849 50.08163959 51.58085294 48.52678042
 50.17258443 51.64890045 50.21910045 51.03953453 50.323161   49.6522571
 50.5086931  50.89558174 48.87628319 50.056997   48.0095188  48.66048817
 50.25579882 50.08786765 48.84652632 49.44060029 50.80411411 50.8589497
 49.87075668 52.080465

In [25]:
mes = np.nanmedian(n_array, axis = 1)

In [26]:
print("the meidan moisture for each hour is: ",mes)

the meidan moisture for each hour is:  [54.355 55.805 52.04  53.735 52.69  52.82  45.65  50.52  55.63  50.34
 47.79  53.92  55.04  46.26  48.25  52.72  55.645 44.76  51.43  41.81
 51.41  50.79  50.5   54.29  46.2   53.66  51.655 37.08  43.3   60.78
 54.45  57.96  49.62  52.69  52.53  48.82  45.29  50.79  59.73  52.945
 53.78  43.015 54.22  53.1   47.37  47.    45.975 47.3   48.23  52.49
 41.93  49.62  53.58  55.78  55.66  53.995 56.81  46.76  45.455 48.09
 50.45  48.67  53.23  48.375 57.66  46.625 48.32  48.98  43.41  51.785
 53.02  52.05  56.29  55.16  52.66  52.34  50.565 56.875 52.46  52.73
 44.35  52.94  51.215 49.34  54.1   52.53  43.97  53.46  54.33  50.37
 53.59  57.43  56.275 51.35  47.19  50.91  48.24  51.165 53.29  51.7
 47.52  49.02  55.685 55.93  44.63  49.055 48.64  44.81  58.81  50.05
 50.315 59.525 40.845 49.145 53.77  43.55  58.475 52.54  44.835 55.87
 47.55  54.26  51.75  48.965 46.715 47.635 51.415 55.55  46.6   41.51
 50.07  45.76  48.33  43.895 43.9   53.395 52.41  

In [33]:
nan_count=np.sum(np.isnan(n_array) , axis = 0)
nan_count.shape

(100,)

In [38]:
np.argmax(nan_count)

np.int64(8)

In [46]:
m = np.nanmax(n_array)
n = np.nanmin(n_array)
print("maximum reading is: ",m,"\n","minimum reading is: ",n)

maximum reading is:  159.93 
 minimum reading is:  -19.93


In [47]:
x_norm = (n_array - n)/(m - n)

In [51]:
x_norm[:5]

array([[0.22873346, 0.48254198, 0.37618147, 0.56983209, 0.22940064,
               nan, 0.28166352, 0.35850106, 0.32814411, 0.55726676,
        0.19737574, 0.33064606, 0.31635717,        nan, 0.57322362,
        0.28372067,        nan, 0.22606472, 0.53953075, 0.54420105,
        0.18831313, 0.54892694, 0.52946736, 0.44223285, 0.28010675,
        0.43784054, 0.60130101, 0.2826087 , 0.33086845, 0.34832648,
        0.31202046, 0.45196264, 0.37834983, 0.34988324, 0.59018125,
        0.36878683, 0.22995663, 0.41849216, 0.42649839, 0.23801846,
        0.50650506, 0.22573112, 0.60986323,        nan, 0.32375181,
        0.24318915, 0.56988769, 0.50822862, 0.4490715 , 0.34927166,
        0.50778383, 0.28638941, 0.51067497, 0.23112421, 0.4581341 ,
        0.58951407, 0.19576337, 0.10269098, 0.41309908, 0.43255866,
        0.44184366,        nan, 0.41293228, 0.51306572, 0.35433115,
               nan, 0.55654398, 0.20571556, 0.22334038, 0.96591794,
        0.40509285, 0.40325809, 0.56999889, 0.48

In [54]:
np.savetxt('sensor_data_normalized.csv' ,x_norm, delimiter=',', fmt='%.4f')